spring.application.name=minimarket

spring.datasource.url=jdbc:h2:file:./data/minimarketdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

spring.ldap.urls=ldap://localhost:389
spring.ldap.base=dc=minimarket,dc=com
spring.ldap.username=cn=admin,dc=minimarket,dc=com
spring.ldap.password=${LDAP_PASSWORD:tu_contraseña_admin}
spring.jpa.defer-datasource-initialization=true